### ISSUE TITLE
Block insecure HTTP using regex on full path

### ISSUE THREAD

**Issue by r3a1d3a1** [enthus1ast/nimSocks#15]
Apple uses insecure (no TLS) OCSP and it'd be great to block only some of those.
Since the whole URL (not just FQDN) is available, a regex would be suitable for such filtering.

**Comment by enthus1ast** [comment]
SOCKS does not know about the data it transports.
This is not an http proxy.

**Comment by enthus1ast** [comment]
If you want it and think it's possible (without a major rewrite) then do it an PR.
